branches:
  only:
  - master
  - stable
language: java
jdk:
- oraclejdk8
before_install: 
install:
- mvn clean install -Dgpg.skip=true
before_script: 
script: 
after_success:
- mvn clean deploy  -Dgpg.skip=true
after_failure:
- cat com.github.lafa.jmetrics/target/surefire-reports/*.txt
- cat com.github.lafa.jmetrics/core/target/surefire-reports/*.txt
env:
  global:
  - secure: cKrfRNIf2sbOaDBP1FK0AaVaATu4cPxUbTDFbeAigf0F2sBfcIJ8acpyNcAZH/lG8HneZHcddfcO5ZulgdJzwn5JwSvw6XoH6xeYMMifslHFQ5M8REkJT0qMOfUK+hrr9Eo/5LiV4wEmtwDjEqsrtcympd2q1G+nqmFlGCAHhzda2T4w9toYdN8RKCf1CCNDMxliYMCbQ80VRWWVWm+c6erY24mgsbPb9IEGf+vq1metGGuYruC2V2vPFwEqFNKR/rRD0XcB9/HHKw4hu7NMcVtdMY8e3+CKRe2LfHa3UfGy5Igg8g7p+yZWAttbxgzER8ZNznR4kOEgG+JC1Dso1TM2sqZ5mNVbR0r3UK0IKFXPKdS+FC77vW0qoCtNJSxWDhYI/W+Xvg6SYFLegamx6C4fHRBF8xHoVA6h39822y0gnp1Gpki1fEoupQISfs0/g6gltX4rmJAidVO4uQo5J9U/TXaeRPEoJDgLvCVhKwXaRxcVkO6fi+0iXyaMozXbuJK6qGoLXd70P8oCLDgdrMFiTNoGKSBnTGeG0+uiQQCmJNRr0RDUMA+2KDdj1ZO6OxstPdT+nuqjvP0O2ri6zRFCIkh20K+h2lboWEGHwYDNSTfTBPir7GTPglz5veL9JJHll4Xid/7V4an3iIzqh1K9x0kVnXwwoYn+vbURKSM=
  - secure: EuLa2JxYLSIrp7hQWKJlGWzR2wXwXVdjFypTeL2CRWcYONORHzndBPf2P9OK98wR48YjRYGnOxYECA0zBQ0+E7IXEJdY4G+31qB4XvIBPndCDRlWccEb4HMQ3gldRKAC/whasOw0D5lDDGfuR+vzAWogaoeuzcLSo4E3TyjYCFtjTqS94i1NgqZZ/AQejot8xZonNKJ9snqplldfRPINip47cuqLWkvLijndC4LnZx48VMDbUUTB3vNO66Q9agg418i74iWnYvqtog4PMtMJQIog6ZVcwh9rlzORYLtKEbOruxwZydPaDLcFHUxuFF4L6xBUGn6gHPjiWvd3SCVFLfwi8+gfTgTZ6/lulympSIVD+X1nAEhJpmZEQUkHQXgAPOLks5PQ72xNjsxpYAKqZ9N/RKYO6Qf1/CwrHESSZ/MvY8ZFkeUTF9KPXfJRloPbG3EpTsT2HJpTTrexXWM2G9g27vHLkiGVULX9ibNLxSvn1qno6UXEBFrYC9ojP4krm8W67OYItKn0r16JhK5JUXEw8ApUb9Ki5MjF3X7zKJyAZvsoC2mwp/B9CMK9/hRjwWz+X0v4Z4UQH+QUWW59mj2/vVyCadzvwpHyhwzv8E8LIwOE119J557pxOJhelK09tm3yYVr/qQlNCVU0VqlbFptKaqb9AN/83/Q+Orfw3M=
  - secure: Qt5DjPi1Wmyp/TDjpSgkUyjXdgmzZbEVDyDKTZ3OTQexU7ws9Le1KE0MGpdjh+I8qYdQy0htnIUVOVcScIKie3WZwWY4fpcq43HrZjklv465oDSqhrm+0Ui7bJdeamPrjumukj+SceOUZ5t0o/oguM35ioiA5hFotsKxuDaa65HZofFnrS5r33hs6g8bbMrndYKbOwzGL+mytlWbts0iqsrjNovZD9PoYzuskJpyiIRuDk0Wp/GPmO3m+aSc+cI+qlcTOez3r2y5W3kiy5upzXrictqjQyJo8H0EjrdR+YoeOEP1chkKDx3wNFzzdhJO6vkpgc+UcfGLVSL26WsL5wrZ7PchgJFl77QrQFhRR39L7XmQjTS+fD1bmb8H6aB31eXwwn1zGPkSJiAAyT4XSj0eA9LLYVIu2iOjri6RNrdZpfMX509dDrTHv3z9/mvC6cR8Szinwtd+NXUjeJjczdlRxJd7IACwYWSTdIrNb5+CJrr/lye1NA1JlkaQvC1MNQlOrPboiDekcnME4sP8SmFgGfkd+OUS8QJVjsQhDEOzjU9UgrqqyrWDYP8qtlA+CCAWBtTvj4nM683OOzQrsOWTRsjCL3c9FQGdphhlwGAz2PBV1Na31FNrDrKwoP/eHqI78azalDbpgZJNZ5DW8MlijXWks3v7oaI7mDZbKs4=
